apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: helloservice
    context: src/helloservice
  - image: frontend
    context: src/frontend
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: false
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/helloservice.yaml
    - ./kubernetes-manifests/frontend.yaml

