apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-bakery
spec:
  selector:
    matchLabels:
      app: frontend-bakery
  template:
    metadata:
      labels:
        app: frontend-bakery
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: default
      containers:
        - name: server
          image: frontend-bakery
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/health"
              port: 8080

          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/health"
              port: 8080

          env:
            - name: PORT
              value: "8080"
            - name: HELLO_SERVICE_ADDR
              value: "helloservice:8080"
            - name: DISABLE_TRACING
              value: "1"
            - name: DISABLE_PROFILER
              value: "1"
            - name: JAEGER_SERVICE_ADDR
              value: "jaeger-collector:14268"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-bakery
spec:
  type: ClusterIP
  selector:
    app: frontend-bakery
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-bakery-external
spec:
  type: LoadBalancer
  selector:
    app: frontend-bakery
  ports:
    - name: http
      port: 80
      targetPort: 8080
